spring.application.name=esientradas

# Logging
logging.level.root=INFO
logging.level.edu.esi.ds.esientradas=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# ==========================================
# BASE DE DATOS - MySQL
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/BackendEntradas_DISOFT_G16?serverTimezone=UTC&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&maxAllowedPacket=134217728
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# HIBERNATE / JPA
# ==========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==========================================
# SERVIDOR
# ==========================================
server.port=8080
server.error.include-message=always
management.endpoints.web.exposure.include=health,info

# ==========================================
# COMUNICACION ENTRE BACKENDS
# ==========================================
esiusuarios.base-url=http://localhost:8081

# ==========================================
# PASARELA DE PAGO (Stripe) - configurado (clave secreta de test)
# ==========================================
stripe.api.key=sk_test_51R3dZvJwHK3ghaTfBoVKV72Y63LVXLfJYMe6hvNv0Gnmd3olteAiIFB3WyNjQn74283AviV3No2FlzWzZbsT8AAd00iZXrdXFY

# ==========================================
# BREVO (SMTP relay) - configurado
# ==========================================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a51558001@smtp-brevo.com
spring.mail.password=xsmtpsib-15661f9d71ef0a4f1a6d798b2a68fb34d4a4a92eb1a8b4f59fd2ad0e81d1f083-ohjEIur8JM7Okghr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Remitente verificado en Brevo
app.mail.sender=alejandro.fdezmunoz2002@gmail.com
